# Cloud Build configuration (alternative to GitHub Actions)
# Use this if you prefer Cloud Build over GitHub Actions

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/presentation-agent:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/presentation-agent:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/presentation-agent:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/presentation-agent:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'presentation-agent'
      - '--image'
      - 'gcr.io/$PROJECT_ID/presentation-agent:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/presentation-agent:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/presentation-agent:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'

